# Need Ubuntu trusty to install pip3
dist: trusty

jdk: oraclejdk8
python: 3.5
language: scala

env:
  global:
    - "HOST_IP=$( (/sbin/ifconfig eth0 2> /dev/null || /sbin/ifconfig venet0:0 2> /dev/null ) | grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}')"
    - DOCKER_HOST=tcp://$HOST_IP:2375
    - DOCKER_PORT_RANGE=2400:2500
    - SLIRP_HOST=$HOST_IP
    - SLIRP_PORTS=$(seq 2375 2500)
    - unset DOCKER_MACHINE_NAME

before_install:
  - sudo sh -c "wget -qO- https://get.docker.io/gpg | apt-key add -"
  - sudo sh -c "echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"

install:
  - sudo apt-get -qqy update
  - sudo apt-get -qqy install slirp python3-setuptools
  - sudo apt-get -qqy install -o Dpkg::Options::="--force-confold" lxc-docker-1.6.0
  - sudo sudo usermod -aG docker "$USER"
  - git clone git://github.com/cptactionhank/sekexe
  - sudo easy_install3 -U pip
  - pip3 install --user conductr-cli
  - sudo /sbin/ifconfig lo:0 192.168.10.1 netmask 255.255.255.0 up
  - sudo /sbin/ifconfig lo:1 192.168.10.2 netmask 255.255.255.0 up
  - sudo /sbin/ifconfig lo:2 192.168.10.3 netmask 255.255.255.0 up
  - sudo /sbin/ifconfig lo:3 192.168.10.4 netmask 255.255.255.0 up
  - ./install-temp-lightbend-credentials.sh
  
before_script:
  - "sekexe/run docker -d -H tcp://0.0.0.0:2375 &"
  - "while ! docker -H tcp://$HOST_IP:2375 info &> /dev/null ; do sleep 1; done"

script:
  - ./bin/create-credentials.sh
  - sbt scripted
